name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'Build mode'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - development
          - test
      no_cache:
        description: 'Disable cache for all tags'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lastthree/last-three-service-package-docker-ui
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            lastthree/last-three-service-package-docker-ui:${{ env.timestamp }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=lastthree/last-three-service-package-docker-ui:buildcache
          cache-to: type=registry,ref=lastthree/last-three-service-package-docker-ui:buildcache,mode=max
          build-args: |
            BUILD_TIMESTAMP=${{ github.run_id }}-${{ github.run_number }}
            NODE_ENV=${{ github.event.inputs.build_mode || 'production' }}
          no-cache: ${{ github.event.inputs.no_cache == 'true' }}

      - name: Push latest tag (always rebuild without cache)
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lastthree/last-three-service-package-docker-ui:latest
          no-cache: true
          build-args: |
            BUILD_TIMESTAMP=${{ github.run_id }}-${{ github.run_number }}
            NODE_ENV=${{ github.event.inputs.build_mode || 'production' }}
